pub const DECISION_EMPHASIS_LOGIT_STEEPNESS: f64 = 2.0;

pub const SELF_CARRY_PHYSICALITY_SENSITIVITY: f64 = 1.0;
pub const SELF_CARRY_AERIALITY_SENSITIVITY: f64 = 0.8;
pub const SELF_CARRY_PASSING_RANGE_SENSITIVITY: f64 = 0.8;
pub const SELF_CARRY_DIRECTNESS_SENSITIVITY: f64 = 0.6;

pub const SHORT_PASS_PASSING_RANGE_SENSITIVITY: f64 = 1.0;
pub const SHORT_PASS_NARROW_WIDTH_SENSITIVITY: f64 = 0.8;
pub const SHORT_PASS_DIRECTNESS_SENSITIVITY: f64 = 0.6;

pub const LONG_LAUNCH_PASSING_RANGE_SENSITIVITY: f64 = 1.0;
pub const LONG_LAUNCH_DIRECTNESS_SENSITIVITY: f64 = 0.8;
pub const LONG_LAUNCH_MENTALITY_SENSITIVITY: f64 = 0.6;

pub const CROSS_AERIALITY_SENSITIVITY: f64 = 1.0;
pub const CROSS_WIDE_WIDTH_SENSITIVITY: f64 = 0.8;
pub const CROSS_PASSING_RANGE_SENSITIVITY: f64 = 0.6;

pub const SELF_FINISH_MENTALITY_SENSITIVITY: f64 = 1.0;
pub const SELF_FINISH_IMPATIENCE_SENSITIVITY: f64 = 1.2;
