pub const TEMPO_SENSITIVITY: f64 = 0.8;
pub const LINE_HEIGHT_SENSITIVITY: f64 = 0.7;
pub const DIRECTNESS_SENSITIVITY: f64 = 0.5;
pub const WIDTH_SENSITIVITY: f64 = 0.4;
pub const PRESSING_SENSITIVITY: f64 = 0.6;
pub const COUNTER_PRESS_SENSITIVITY: f64 = 0.4;
pub const AGGRESSION_SENSITIVITY: f64 = 0.3;
pub const COUNTER_ATTACK_SENSITIVITY: f64 = 0.5;