pub const DRIVE_SCARCITY_SERIES_LIMIT: u32 = 3;
pub const SERIES_MAX_DOWNS: u8 = 4;
pub const SERIES_TARGET_ADVANCE_MIRIM: f64 = 10.0;

pub const EPV_SELF_CARRY_PROXIMITY_BONUS: f64 = 0.05;
pub const EPV_SHORT_PASS_PROXIMITY_BONUS: f64 = 0.06;
pub const EPV_LONG_LAUNCH_PROXIMITY_BONUS: f64 = 0.15;

pub const EPV_SELF_CARRY_ADVANCE_MIRIM: f64 = 5.0;
pub const EPV_SHORT_PASS_ADVANCE_MIRIM: f64 = 6.0;
pub const EPV_LONG_LAUNCH_ADVANCE_MIRIM: f64 = 15.0;

pub const EPV_EPA_DIFF_MULTIPLIER: f64 = 2.0;

pub const OPPORTUNITY_EVALUATION_DEFAULT_RATING: f64 = 10.0;
pub const FIELD_POINT_OPPORTUNITY_ADVANCE_BUFFER_MIRIM: f64 = 3.0;

pub const CARRY_FORWARD_TARGET_OFFSET_MIRIM: f64 = 10.0;
pub const CARRY_HELPER_OFFSET_FACTOR: f64 = 0.7;
pub const CARRY_ARTRO_SEARCH_MARGIN_MIRIM: f64 = 1.5;

pub const INTERCEPTION_BASE_THRESHOLD: f64 = 2.5;
pub const INTERCEPTION_HANDS_DIFF_WEIGHT: f64 = 0.2;
pub const INTERCEPTION_ANTICIPATION_WEIGHT: f64 = 0.1;
pub const INTERCEPTION_CLAMP_MIN: f64 = -2.0;
pub const INTERCEPTION_CLAMP_MAX: f64 = 3.0;

pub const CENTRAL_ZONE_NORMALIZED_Y_FALLBACK: f64 = 0.5;
pub const CENTRAL_ZONE_NORMALIZED_Y_MIN: f64 = 0.25;
pub const CENTRAL_ZONE_NORMALIZED_Y_MAX: f64 = 0.75;
pub const BLOCK_BONUS_MULTIPLIER: f64 = 0.35;
pub const BLOCK_BONUS_MIN: f64 = 0.5;
