[package]
name = "arlo-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arlo-domain.workspace = true
arlo-math.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde.workspace = true
uuid.workspace = true