MIN_CURRENT_ABILITY = 1
MAX_CURRENT_ABILITY = 200
ATTRIBUTE_MIN = 1.0
ATTRIBUTE_MAX = 20.0
CA_FORMULA_MULTIPLIER = 10.0
CA_FORMULA_OFFSET = 0.0
ATTRIBUTE_SATURATION_THRESHOLD = 15.0
ATTRIBUTE_SATURATION_MULTIPLIER = 1.2