[package]
name = "arlo-recovery"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arlo-db.workspace = true
arlo-domain.workspace = true
arlo-engine.workspace = true
arlo-events.workspace = true
arlo-persistence.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true