[package]
name = "arlo-controller"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arlo-domain.workspace = true
arlo-db.workspace = true
arlo-engine.workspace = true
arlo-persistence.workspace = true
rand.workspace = true
rayon.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
uuid.workspace = true