CREATE TEMP TABLE injury_profile_assignments (code TEXT PRIMARY KEY, profile_class TEXT NOT NULL);

INSERT INTO injury_profile_assignments (code, profile_class) VALUES
    ('ANKLE_ACHILLES_TENDINOPATHY_INSERTIONAL', 'overuse'),
    ('ANKLE_ACHILLES_TENDINOPATHY_MIDPORTION', 'overuse'),
    ('ANKLE_ANTERIOR_IMPINGEMENT', 'chronic_flare'),
    ('ANKLE_CHRONIC_ANKLE_INSTABILITY', 'chronic_flare'),
    ('ANKLE_HIGH_ANKLE_SPRAIN_CONTACT', 'ligament_sprain'),
    ('ANKLE_OSTEOARTHRITIS', 'chronic_flare'),
    ('ANKLE_OSTEOCHONDRAL_LESION_TALUS', 'structural_tear'),
    ('ANKLE_PERONEAL_TENDINOPATHY_ANKLE', 'overuse'),
    ('ANKLE_POSTERIOR_IMPINGEMENT', 'chronic_flare'),
    ('ANKLE_POSTERIOR_TIBIAL_TENDON_DYSFUNCTION', 'chronic_flare'),
    ('ANKLE_TARSAL_TUNNEL_SYNDROME', 'nerve'),
    ('ANKLE_TIBIALIS_ANTERIOR_TENDINOPATHY', 'overuse'),
    ('ANKLE_TIBIALIS_POSTERIOR_RUPTURE', 'structural_surgical'),
    ('ARM_ACUTE_COMPARTMENT_SYNDROME', 'medical_emergency'),
    ('ARM_BICEPS_TENDINOPATHY', 'overuse'),
    ('ARM_BRACHIAL_ARTERY_INJURY', 'vascular_emergency'),
    ('ARM_CUBITAL_TUNNEL_SYNDROME', 'nerve'),
    ('ARM_ELBOW_OSTEOARTHRITIS', 'chronic_flare'),
    ('ARM_LATERAL_EPICONDYLITIS', 'overuse'),
    ('ARM_MYOSITIS_OSSIFICANS', 'myositis'),
    ('ARM_OSTEOCHONDRITIS_DISSECANS_ELBOW', 'structural_tear'),
    ('ARM_PRONATOR_TERES_SYNDROME', 'nerve'),
    ('ARM_RADIAL_TUNNEL_SYNDROME', 'nerve'),
    ('ARM_TRICEPS_TENDINOPATHY', 'overuse'),
    ('ARM_ULNAR_NERVE_INJURY_TRAUMATIC', 'nerve'),
    ('CALF_ACHILLES_TENDINOPATHY', 'overuse'),
    ('CALF_CHRONIC_EXERTIONAL_COMPARTMENT_SYNDROME', 'chronic_flare'),
    ('CALF_COMPARTMENT_SYNDROME_LEG', 'medical_emergency'),
    ('CALF_DEEP_VEIN_THROMBOSIS', 'medical_emergency'),
    ('CALF_GASTROCNEMIUS_STRAIN', 'muscle_strain'),
    ('CALF_GASTROCNEMIUS_TEAR_TRAUMATIC', 'structural_tear'),
    ('CALF_MTSS_SHIN_SPLINTS', 'overuse'),
    ('CALF_PERONEAL_TENDINOPATHY', 'overuse'),
    ('CALF_POPLITEAL_ARTERY_ENTRAPMENT', 'structural_surgical'),
    ('CALF_POSTERIOR_TIBIAL_TENDINOPATHY', 'overuse'),
    ('CALF_SOLEUS_TEAR_TRAUMATIC', 'structural_tear'),
    ('CALF_TIBIAL_ARTERY_INJURY', 'vascular_emergency'),
    ('FOOT_ATHLETES_FOOT', 'infection_mild'),
    ('FOOT_CAVUS_FOOT_SYMPTOMATIC', 'chronic_flare'),
    ('FOOT_CLAW_TOE', 'chronic_flare'),
    ('FOOT_DIABETIC_FOOT_COMPLICATIONS', 'medical_emergency'),
    ('FOOT_FLAT_FEET_SYMPTOMATIC', 'chronic_flare'),
    ('FOOT_HALLUX_RIGIDUS', 'chronic_flare'),
    ('FOOT_HALLUX_VALGUS', 'chronic_flare'),
    ('FOOT_HAMMER_TOE', 'chronic_flare'),
    ('FOOT_INGROWN_TOENAIL', 'infection_mild'),
    ('FOOT_LISFRANC_INJURY', 'structural_surgical'),
    ('FOOT_METATARSALGIA', 'chronic_flare'),
    ('FOOT_MORTONS_NEUROMA', 'chronic_flare'),
    ('FOOT_NAIL_BED_INJURY_FOOT', 'wound'),
    ('FOOT_OSTEOARTHRITIS_FOOT', 'chronic_flare'),
    ('FOOT_PERONEAL_TENDON_SUBLUXATION_FOOT', 'joint'),
    ('FOOT_PLANTAR_FASCIITIS', 'overuse'),
    ('FOOT_PLANTAR_PLATE_TEAR', 'structural_tear'),
    ('FOOT_PLANTAR_WARTS', 'infection_mild'),
    ('FOOT_POSTERIOR_TIBIAL_TENDON_DYSFUNCTION_FOOT', 'chronic_flare'),
    ('FOOT_PUNCTURE_WOUND', 'wound'),
    ('FOOT_SESAMOIDITIS', 'overuse'),
    ('FOOT_TURF_TOE_NONCONTACT', 'ligament_sprain'),
    ('GROIN_ADDUCTOR_TENDINOPATHY', 'overuse'),
    ('GROIN_FEMORAL_HERNIA', 'hernia'),
    ('GROIN_GILMORE_GROIN', 'hernia'),
    ('GROIN_OSTEITIS_PUBIS', 'overuse'),
    ('GROIN_PECTINEUS_STRAIN', 'muscle_strain'),
    ('GROIN_PENILE_INJURY', 'wound'),
    ('GROIN_TESTICULAR_TORSION_TRAUMATIC', 'urgent_surgery'),
    ('HAND_CARPAL_TUNNEL_SYNDROME', 'nerve'),
    ('HAND_COMPLEX_REGIONAL_PAIN_SYNDROME', 'chronic_flare'),
    ('HAND_DE_QUERVAIN_TENOSYNOVITIS', 'joint'),
    ('HAND_DIGITAL_NERVE_LACERATION', 'wound'),
    ('HAND_DUPUYTREN_CONTRACTURE', 'chronic_flare'),
    ('HAND_EXTENSOR_TENDINOPATHY', 'overuse'),
    ('HAND_FLEXOR_TENDINOPATHY', 'overuse'),
    ('HAND_FLEXOR_TENDON_LACERATION', 'structural_surgical'),
    ('HAND_GANGLION_CYST', 'joint'),
    ('HAND_INTERSECTION_SYNDROME', 'chronic_flare'),
    ('HAND_KIENBOCK_DISEASE', 'bone_disorder'),
    ('HAND_NAIL_BED_INJURY', 'wound'),
    ('HAND_OSTEOARTHRITIS', 'chronic_flare'),
    ('HAND_PARTIAL_AMPUTATION_FINGER', 'structural_surgical'),
    ('HAND_TFCC_TEAR', 'structural_tear'),
    ('HAND_THUMB_UCL_TEAR', 'structural_tear'),
    ('HAND_TRIGGER_FINGER', 'chronic_flare'),
    ('HEAD_ALTITUDE_SICKNESS', 'transient_medical'),
    ('HEAD_BACTERIAL_MENINGITIS', 'infection_critical'),
    ('HEAD_BPPV', 'chronic_flare'),
    ('HEAD_CLUSTER_HEADACHE', 'chronic_flare'),
    ('HEAD_DENTAL_FRACTURE', 'dental'),
    ('HEAD_ENCEPHALITIS', 'infection_critical'),
    ('HEAD_EPIDURAL_HEMATOMA', 'neuro_emergency'),
    ('HEAD_EXERCISE_INDUCED_SEIZURE', 'medical_emergency'),
    ('HEAD_FACIAL_NERVE_PALSY', 'nerve'),
    ('HEAD_HEAT_EXHAUSTION', 'transient_medical'),
    ('HEAD_HEAT_STROKE', 'medical_emergency'),
    ('HEAD_HIGH_ALTITUDE_CEREBRAL_EDEMA', 'neuro_emergency'),
    ('HEAD_HYPHEMA', 'eye_injury'),
    ('HEAD_HYPOTHERMIA', 'transient_medical'),
    ('HEAD_IDIOPATHIC_INTRACRANIAL_HYPERTENSION', 'medical_emergency'),
    ('HEAD_LABYRINTHITIS', 'infection_moderate'),
    ('HEAD_MIGRAINE', 'transient'),
    ('HEAD_RETROBULBAR_HEMORRHAGE', 'urgent_surgery'),
    ('HEAD_SECOND_IMPACT_SYNDROME', 'neuro_emergency'),
    ('HEAD_SEPTAL_HEMATOMA', 'eye_injury'),
    ('HEAD_SUBARACHNOID_HEMORRHAGE', 'neuro_emergency'),
    ('HEAD_SUBDURAL_HEMATOMA_CHRONIC', 'neuro_emergency'),
    ('HEAD_TENSION_HEADACHE', 'transient'),
    ('HEAD_TRANSIENT_GLOBAL_AMNESIA', 'chronic_flare'),
    ('HEAD_TRIGEMINAL_NEUROPATHY', 'nerve'),
    ('HEAD_VESTIBULAR_MIGRAINE', 'transient'),
    ('HEAD_VESTIBULAR_NEURITIS', 'chronic_flare'),
    ('HEAD_VIRAL_MENINGITIS', 'infection_moderate'),
    ('HIP_ABDUCTOR_TENDINOPATHY', 'overuse'),
    ('HIP_AVASCULAR_NECROSIS_FEMORAL_HEAD', 'bone_disorder'),
    ('HIP_DEEP_GLUTEAL_SYNDROME', 'chronic_flare'),
    ('HIP_FEMOROACETABULAR_IMPINGEMENT', 'chronic_flare'),
    ('HIP_GREATER_TROCHANTERIC_BURSITIS_TRAUMATIC', 'chronic_flare'),
    ('HIP_GREATER_TROCHANTERIC_PAIN_SYNDROME', 'chronic_flare'),
    ('HIP_ILIOFEMORAL_LIGAMENT_SPRAIN', 'ligament_sprain'),
    ('HIP_LABRAL_TEAR_DEGENERATIVE', 'chronic_flare'),
    ('HIP_OSTEOARTHRITIS', 'chronic_flare'),
    ('HIP_PIRIFORMIS_SYNDROME', 'chronic_flare'),
    ('HIP_SLIPPED_CAPITAL_FEMORAL_EPIPHYSIS', 'structural_surgical'),
    ('HIP_SNAPPING_HIP_SYNDROME', 'chronic_flare'),
    ('KNEE_BAKERS_CYST', 'joint'),
    ('KNEE_CHONDROMALACIA_PATELLAE', 'chronic_flare'),
    ('KNEE_FAT_PAD_SYNDROME', 'joint'),
    ('KNEE_GOUT', 'chronic_flare'),
    ('KNEE_HEMARTHROSIS', 'joint'),
    ('KNEE_INFRAPATELLAR_BURSITIS', 'chronic_flare'),
    ('KNEE_ITB_SYNDROME', 'overuse'),
    ('KNEE_LCL_TEAR', 'structural_tear'),
    ('KNEE_MENISCUS_DEGENERATION', 'chronic_flare'),
    ('KNEE_OSTEOARTHRITIS', 'chronic_flare'),
    ('KNEE_OSTEOCHONDRITIS_DISSECANS', 'structural_tear'),
    ('KNEE_PATELLAR_TENDINOPATHY', 'overuse'),
    ('KNEE_PATELLOFEMORAL_PAIN_SYNDROME', 'chronic_flare'),
    ('KNEE_PCL_TEAR', 'structural_tear'),
    ('KNEE_PES_ANSERINE_BURSITIS', 'chronic_flare'),
    ('KNEE_PLICA_SYNDROME', 'chronic_flare'),
    ('KNEE_POPLITEUS_TENDINOPATHY', 'overuse'),
    ('KNEE_PREPATELLAR_BURSITIS', 'chronic_flare'),
    ('KNEE_QUADRICEPS_TENDINOPATHY_KNEE', 'overuse'),
    ('KNEE_RECURRENT_PATELLAR_INSTABILITY', 'chronic_flare'),
    ('KNEE_SEPTIC_ARTHRITIS', 'medical_emergency'),
    ('KNEE_SINDING_LARSEN_JOHANSSON', 'overuse'),
    ('NECK_BRACHIAL_PLEXUS_INJURY', 'nerve'),
    ('NECK_CAROTID_ARTERY_INJURY', 'vascular_emergency'),
    ('NECK_CERVICALGIA', 'chronic_flare'),
    ('NECK_CERVICAL_FACET_SYNDROME', 'chronic_flare'),
    ('NECK_CERVICAL_MYELOPATHY', 'nerve'),
    ('NECK_CERVICAL_SPONDYLOLISTHESIS', 'bone_disorder'),
    ('NECK_DEGENERATIVE_DISC_DISEASE', 'chronic_flare'),
    ('NECK_JUGULAR_VEIN_INJURY', 'vascular_emergency'),
    ('NECK_LONGUS_COLLI_STRAIN', 'muscle_strain'),
    ('NECK_SPINAL_CORD_INJURY', 'neuro_emergency'),
    ('NECK_THORACIC_OUTLET_SYNDROME', 'nerve'),
    ('NECK_TORTICOLLIS', 'chronic_flare'),
    ('NECK_TRACHEAL_INJURY', 'organ_emergency'),
    ('NECK_VERTEBRAL_ARTERY_DISSECTION', 'vascular_emergency'),
    ('SHOULDER_ADHESIVE_CAPSULITIS', 'chronic_flare'),
    ('SHOULDER_AXILLARY_NERVE_INJURY', 'nerve'),
    ('SHOULDER_BICEPS_TENDINOPATHY', 'overuse'),
    ('SHOULDER_LONG_THORACIC_NERVE_PALSY', 'nerve'),
    ('SHOULDER_MULTIDIRECTIONAL_INSTABILITY', 'joint'),
    ('SHOULDER_OSTEOARTHRITIS', 'chronic_flare'),
    ('SHOULDER_PARSONAGE_TURNER_SYNDROME', 'chronic_flare'),
    ('SHOULDER_ROTATOR_CUFF_TENDINOPATHY', 'overuse'),
    ('SHOULDER_SCAPULAR_DYSKINESIS', 'chronic_flare'),
    ('SHOULDER_SUBACROMIAL_IMPINGEMENT', 'overuse'),
    ('SHOULDER_SUPRASCAPULAR_NEUROPATHY', 'nerve'),
    ('THIGH_ADDUCTOR_MAGNUS_TEAR', 'structural_tear'),
    ('THIGH_COMPARTMENT_SYNDROME_THIGH', 'medical_emergency'),
    ('THIGH_DOMS', 'transient'),
    ('THIGH_EXERCISE_INDUCED_MYOPATHY', 'medical_emergency'),
    ('THIGH_FEMORAL_ARTERY_INJURY', 'vascular_emergency'),
    ('THIGH_FEMORAL_NEUROPATHY', 'nerve'),
    ('THIGH_HAMSTRING_STRAIN_GRADE2', 'muscle_strain'),
    ('THIGH_HAMSTRING_STRAIN_GRADE3', 'muscle_strain'),
    ('THIGH_HAMSTRING_TENDINOPATHY', 'overuse'),
    ('THIGH_ITB_SYNDROME_PROXIMAL', 'overuse'),
    ('THIGH_MERALGIA_PARESTHETICA', 'nerve'),
    ('THIGH_QUADRICEPS_TENDINOPATHY', 'overuse'),
    ('THIGH_RECTUS_FEMORIS_STRAIN', 'muscle_strain'),
    ('THIGH_RHABDOMYOLYSIS_THIGH', 'medical_emergency'),
    ('THIGH_SCIATIC_NERVE_INJURY', 'nerve'),
    ('TRUNK_ANKYLOSING_SPONDYLITIS', 'chronic_flare'),
    ('TRUNK_AORTIC_RUPTURE', 'vascular_emergency'),
    ('TRUNK_APPENDICITIS', 'structural_surgical'),
    ('TRUNK_BOWEL_PERFORATION', 'organ_emergency'),
    ('TRUNK_CHRONIC_LOW_BACK_PAIN', 'chronic_flare'),
    ('TRUNK_COMMOTIO_CORDIS', 'neuro_emergency'),
    ('TRUNK_COSTOCHONDRITIS', 'chronic_flare'),
    ('TRUNK_DIAPHRAGMATIC_RUPTURE', 'organ_emergency'),
    ('TRUNK_EXERCISE_INDUCED_ANAPHYLAXIS', 'medical_emergency'),
    ('TRUNK_EXERCISE_INDUCED_BRONCHOSPASM', 'transient_medical'),
    ('TRUNK_FLAIL_CHEST', 'organ_emergency'),
    ('TRUNK_HEPATITIS_A', 'infection_moderate'),
    ('TRUNK_HEPATITIS_B', 'infection_moderate'),
    ('TRUNK_HYPONATREMIA', 'medical_emergency'),
    ('TRUNK_INTERCOSTAL_NEURALGIA', 'nerve'),
    ('TRUNK_KIDNEY_LACERATION', 'organ_emergency'),
    ('TRUNK_KIDNEY_STONES', 'transient_medical'),
    ('TRUNK_LIVER_LACERATION', 'organ_emergency'),
    ('TRUNK_OBLIQUE_STRAIN', 'muscle_strain'),
    ('TRUNK_OSTEITIS_PUBIS', 'overuse'),
    ('TRUNK_PNEUMOTHORAX', 'organ_emergency'),
    ('TRUNK_RED_BLOOD_CELL_SICKLING', 'medical_emergency'),
    ('TRUNK_RHABDOMYOLYSIS', 'medical_emergency'),
    ('TRUNK_SCIATICA', 'nerve'),
    ('TRUNK_SCOLIOSIS_SYMPTOMATIC', 'chronic_flare'),
    ('TRUNK_SICKLE_CELL_TRAIT_CRISIS', 'medical_emergency'),
    ('TRUNK_SLIPPING_RIB_SYNDROME', 'chronic_flare'),
    ('TRUNK_SPINAL_CORD_INJURY_THORACOLUMBAR', 'neuro_emergency'),
    ('TRUNK_SPLENIC_MONONUCLEOSIS_COMPLICATION', 'medical_emergency'),
    ('TRUNK_SPLENIC_RUPTURE', 'organ_emergency'),
    ('TRUNK_SPORTS_HERNIA', 'hernia'),
    ('TRUNK_TENSION_PNEUMOTHORAX', 'organ_emergency');

CREATE TEMP TABLE injury_profile_templates (
    profile_class TEXT NOT NULL,
    severity_grade TEXT NOT NULL,
    treatment_kind TEXT NOT NULL,
    minimum_days INTEGER NOT NULL,
    typical_days INTEGER NOT NULL,
    maximum_days INTEGER NOT NULL,
    mandatory_withdrawal BOOLEAN NOT NULL
);

INSERT INTO injury_profile_templates
    (profile_class, severity_grade, treatment_kind, minimum_days, typical_days, maximum_days, mandatory_withdrawal)
VALUES
    ('overuse', 'Grade1', 'Conservative', 14, 35, 90, 0),
    ('chronic_flare', 'Grade1', 'Conservative', 3, 14, 45, 0),
    ('ligament_sprain', 'Grade1', 'Conservative', 7, 21, 42, 0),
    ('ligament_sprain', 'Grade2', 'Conservative', 28, 56, 100, 0),
    ('ligament_sprain', 'Grade3', 'Conservative', 70, 120, 210, 1),
    ('structural_tear', 'Grade1', 'Conservative', 21, 45, 90, 0),
    ('structural_tear', 'Grade2', 'Conservative', 60, 120, 210, 0),
    ('structural_tear', 'Grade3', 'Conservative', 120, 240, 365, 1),
    ('nerve', 'Grade1', 'Conservative', 14, 30, 60, 0),
    ('nerve', 'Grade2', 'Conservative', 45, 90, 180, 1),
    ('nerve', 'Grade3', 'Conservative', 120, 240, 450, 1),
    ('structural_surgical', 'Grade2', 'Surgical', 60, 120, 240, 1),
    ('structural_surgical', 'Grade3', 'Surgical', 120, 240, 450, 1),
    ('medical_emergency', 'Grade2', 'Conservative', 14, 45, 90, 1),
    ('medical_emergency', 'Grade3', 'Conservative', 45, 120, 240, 1),
    ('vascular_emergency', 'Grade3', 'Surgical', 180, 365, 730, 1),
    ('myositis', 'Grade1', 'Conservative', 30, 60, 120, 0),
    ('myositis', 'Grade2', 'Conservative', 60, 120, 240, 0),
    ('myositis', 'Grade3', 'Conservative', 90, 180, 365, 1),
    ('muscle_strain', 'Grade1', 'Conservative', 7, 14, 28, 0),
    ('muscle_strain', 'Grade2', 'Conservative', 21, 42, 75, 0),
    ('muscle_strain', 'Grade3', 'Conservative', 60, 100, 180, 1),
    ('infection_mild', 'Grade1', 'Conservative', 3, 7, 14, 0),
    ('wound', 'Grade1', 'Conservative', 3, 10, 21, 0),
    ('wound', 'Grade2', 'Conservative', 14, 30, 60, 1),
    ('wound', 'Grade3', 'Conservative', 45, 90, 150, 1),
    ('joint', 'Grade1', 'Conservative', 7, 21, 42, 0),
    ('joint', 'Grade2', 'Conservative', 30, 60, 120, 0),
    ('joint', 'Grade3', 'Conservative', 90, 150, 270, 1),
    ('hernia', 'Grade1', 'Conservative', 21, 45, 90, 0),
    ('hernia', 'Grade2', 'Conservative', 60, 120, 180, 1),
    ('urgent_surgery', 'Grade2', 'Surgical', 30, 75, 150, 1),
    ('urgent_surgery', 'Grade3', 'Surgical', 90, 150, 240, 1),
    ('bone_disorder', 'Grade1', 'Conservative', 30, 60, 120, 0),
    ('bone_disorder', 'Grade2', 'Conservative', 90, 150, 240, 1),
    ('bone_disorder', 'Grade3', 'Conservative', 180, 300, 540, 1),
    ('transient_medical', 'Grade1', 'Conservative', 1, 3, 7, 1),
    ('transient_medical', 'Grade2', 'Conservative', 7, 14, 30, 1),
    ('infection_critical', 'Grade3', 'Conservative', 45, 90, 180, 1),
    ('dental', 'Grade1', 'Conservative', 3, 7, 14, 0),
    ('dental', 'Grade2', 'Conservative', 7, 14, 30, 1),
    ('dental', 'Grade3', 'Conservative', 14, 30, 60, 1),
    ('neuro_emergency', 'Grade3', 'Conservative', 180, 365, 730, 1),
    ('eye_injury', 'Grade1', 'Conservative', 7, 14, 30, 1),
    ('eye_injury', 'Grade2', 'Conservative', 21, 45, 90, 1),
    ('infection_moderate', 'Grade2', 'Conservative', 21, 45, 90, 1),
    ('transient', 'Grade1', 'Conservative', 1, 3, 7, 0),
    ('organ_emergency', 'Grade3', 'Surgical', 60, 150, 300, 1);

INSERT INTO injury_recovery_profiles
    (injury_definition_id, severity_grade, treatment_kind, minimum_days, typical_days, maximum_days, mandatory_withdrawal)
SELECT d.id, t.severity_grade, t.treatment_kind, t.minimum_days,
    t.typical_days, t.maximum_days, t.mandatory_withdrawal
FROM injury_profile_assignments a
JOIN injury_definitions d ON d.code = a.code
JOIN injury_profile_templates t ON t.profile_class = a.profile_class
WHERE NOT EXISTS (
    SELECT 1 FROM injury_recovery_profiles existing
    WHERE existing.injury_definition_id = d.id
      AND existing.severity_grade = t.severity_grade
      AND existing.treatment_kind = t.treatment_kind
);

UPDATE outside_match_injury_definitions
SET severity_grade = (
    SELECT MIN(t.severity_grade)
    FROM injury_profile_assignments a
    JOIN injury_definitions d ON d.code = a.code
    JOIN injury_profile_templates t ON t.profile_class = a.profile_class
    WHERE d.id = outside_match_injury_definitions.injury_definition_id
)
WHERE injury_definition_id IN (
    SELECT d.id FROM injury_profile_assignments a
    JOIN injury_definitions d ON d.code = a.code
);

UPDATE injury_definitions
SET relative_frequency = MIN(relative_frequency, 0.01)
WHERE code IN (
    SELECT code FROM injury_profile_assignments
    WHERE profile_class IN ('vascular_emergency', 'neuro_emergency', 'organ_emergency')
);

UPDATE injury_definitions
SET relative_frequency = MIN(relative_frequency, 0.02)
WHERE code IN (
    SELECT code FROM injury_profile_assignments
    WHERE profile_class = 'medical_emergency'
);

DROP TABLE injury_profile_templates;
DROP TABLE injury_profile_assignments;
