CREATE TEMP TABLE retired_injury_ids (id TEXT PRIMARY KEY);

INSERT INTO retired_injury_ids (id)
SELECT injury_definition_id
FROM outside_match_injury_definitions
WHERE daily_weight = 0;

INSERT OR IGNORE INTO retired_injury_ids (id)
SELECT id
FROM injury_definitions
WHERE code IN (
    'ANKLE_ANTERIOR_IMPINGEMENT',
    'ANKLE_POSTERIOR_IMPINGEMENT',
    'ANKLE_POSTERIOR_TIBIAL_TENDON_DYSFUNCTION',
    'ANKLE_SINUS_TARSI_SYNDROME',
    'ANKLE_SYNOVITIS',
    'ANKLE_TARSAL_TUNNEL_SYNDROME',
    'ARM_CUBITAL_TUNNEL_SYNDROME',
    'ARM_LATERAL_EPICONDYLITIS',
    'ARM_LITTLE_LEAGUE_ELBOW',
    'ARM_MEDIAL_EPICONDYLITIS',
    'ARM_MYOSITIS_OSSIFICANS',
    'ARM_OSTEOCHONDRITIS_DISSECANS_ELBOW',
    'ARM_PRONATOR_TERES_SYNDROME',
    'ARM_RADIAL_TUNNEL_SYNDROME',
    'CALF_DEEP_VEIN_THROMBOSIS',
    'CALF_FIBULAR_STRESS_FRACTURE',
    'CALF_POPLITEAL_ARTERY_ENTRAPMENT',
    'CALF_TIBIAL_STRESS_FRACTURE',
    'FOOT_CAVUS_FOOT_SYMPTOMATIC',
    'FOOT_CLAW_TOE',
    'FOOT_DIABETIC_FOOT_COMPLICATIONS',
    'FOOT_HALLUX_RIGIDUS',
    'FOOT_METATARSAL_STRESS_FRACTURE',
    'FOOT_NAVICULAR_STRESS_FRACTURE',
    'FOOT_POSTERIOR_TIBIAL_TENDON_DYSFUNCTION_FOOT',
    'FOOT_PUNCTURE_WOUND',
    'FOOT_SESAMOIDITIS',
    'GROIN_FEMORAL_HERNIA',
    'GROIN_GILMORE_GROIN',
    'GROIN_OSTEITIS_PUBIS',
    'HAND_CARPAL_TUNNEL_SYNDROME',
    'HAND_COMPLEX_REGIONAL_PAIN_SYNDROME',
    'HAND_DE_QUERVAIN_TENOSYNOVITIS',
    'HAND_DIGITAL_NERVE_LACERATION',
    'HAND_FLEXOR_TENDON_LACERATION',
    'HAND_GANGLION_CYST',
    'HAND_KIENBOCK_DISEASE',
    'HAND_PARTIAL_AMPUTATION_FINGER',
    'HAND_TRIGGER_FINGER',
    'HEAD_ALTITUDE_SICKNESS',
    'HEAD_BPPV',
    'HEAD_CLUSTER_HEADACHE',
    'HEAD_EXERCISE_INDUCED_SEIZURE',
    'HEAD_HEAT_EXHAUSTION',
    'HEAD_HEAT_STROKE',
    'HEAD_HIGH_ALTITUDE_CEREBRAL_EDEMA',
    'HEAD_HYPOTHERMIA',
    'HEAD_IDIOPATHIC_INTRACRANIAL_HYPERTENSION',
    'HEAD_LABYRINTHITIS',
    'HEAD_SECOND_IMPACT_SYNDROME',
    'HEAD_TRANSIENT_GLOBAL_AMNESIA',
    'HEAD_VESTIBULAR_NEURITIS',
    'HIP_AVASCULAR_NECROSIS_FEMORAL_HEAD',
    'HIP_DEEP_GLUTEAL_SYNDROME',
    'HIP_FEMOROACETABULAR_IMPINGEMENT',
    'HIP_GREATER_TROCHANTERIC_PAIN_SYNDROME',
    'HIP_PIRIFORMIS_SYNDROME',
    'HIP_SLIPPED_CAPITAL_FEMORAL_EPIPHYSIS',
    'HIP_SNAPPING_HIP_SYNDROME',
    'KNEE_BAKERS_CYST',
    'KNEE_FAT_PAD_SYNDROME',
    'KNEE_GOUT',
    'KNEE_OSGOOD_SCHLATTER',
    'KNEE_OSTEOCHONDRITIS_DISSECANS',
    'KNEE_PLICA_SYNDROME',
    'KNEE_SEPTIC_ARTHRITIS',
    'KNEE_SINDING_LARSEN_JOHANSSON',
    'NECK_CERVICAL_FACET_SYNDROME',
    'NECK_CERVICAL_MYELOPATHY',
    'NECK_CERVICAL_RADICULOPATHY',
    'NECK_CERVICAL_SPONDYLOLISTHESIS',
    'NECK_THORACIC_OUTLET_SYNDROME',
    'SHOULDER_ADHESIVE_CAPSULITIS',
    'SHOULDER_AXILLARY_NERVE_INJURY',
    'SHOULDER_CALCIFIC_TENDINITIS',
    'SHOULDER_LONG_THORACIC_NERVE_PALSY',
    'SHOULDER_MULTIDIRECTIONAL_INSTABILITY',
    'SHOULDER_PARSONAGE_TURNER_SYNDROME',
    'SHOULDER_SUPRASCAPULAR_NEUROPATHY',
    'THIGH_EXERCISE_INDUCED_MYOPATHY',
    'THIGH_FEMORAL_NEUROPATHY',
    'THIGH_ITB_SYNDROME_PROXIMAL',
    'THIGH_MERALGIA_PARESTHETICA',
    'TRUNK_ANKYLOSING_SPONDYLITIS',
    'TRUNK_COMMOTIO_CORDIS',
    'TRUNK_COSTOCHONDRITIS',
    'TRUNK_DEHYDRATION',
    'TRUNK_EXERCISE_INDUCED_ANAPHYLAXIS',
    'TRUNK_HYPONATREMIA',
    'TRUNK_INTERCOSTAL_NEURALGIA',
    'TRUNK_KIDNEY_STONES',
    'TRUNK_OSTEITIS_PUBIS',
    'TRUNK_RED_BLOOD_CELL_SICKLING',
    'TRUNK_SCIATICA',
    'TRUNK_SICKLE_CELL_TRAIT_CRISIS',
    'TRUNK_SLIPPING_RIB_SYNDROME',
    'TRUNK_SPLENIC_MONONUCLEOSIS_COMPLICATION',
    'TRUNK_SPORTS_HERNIA'
);

UPDATE injury_definitions
SET relative_frequency = 0
WHERE id IN (SELECT id FROM retired_injury_ids)
  AND (id IN (SELECT injury_definition_id FROM player_injury_history)
       OR id IN (SELECT injury_definition_id FROM match_injuries));

INSERT OR IGNORE INTO outside_match_injury_definitions
    (injury_definition_id, daily_weight, severity_grade)
SELECT d.id, 0, MIN(p.severity_grade)
FROM injury_definitions d
JOIN injury_recovery_profiles p ON p.injury_definition_id = d.id
WHERE d.id IN (SELECT id FROM retired_injury_ids)
  AND d.relative_frequency = 0
GROUP BY d.id;

DELETE FROM match_injury_grade_floors
WHERE injury_definition_id IN (SELECT id FROM retired_injury_ids);

DELETE FROM outside_match_injury_definitions
WHERE injury_definition_id IN (
    SELECT id FROM retired_injury_ids
    WHERE id NOT IN (SELECT injury_definition_id FROM player_injury_history)
      AND id NOT IN (SELECT injury_definition_id FROM match_injuries)
);

DELETE FROM injury_recovery_profiles
WHERE injury_definition_id IN (
    SELECT id FROM retired_injury_ids
    WHERE id NOT IN (SELECT injury_definition_id FROM player_injury_history)
      AND id NOT IN (SELECT injury_definition_id FROM match_injuries)
);

DELETE FROM injury_definitions
WHERE id IN (SELECT id FROM retired_injury_ids)
  AND id NOT IN (SELECT injury_definition_id FROM player_injury_history)
  AND id NOT IN (SELECT injury_definition_id FROM match_injuries);

DROP TABLE retired_injury_ids;
