[package]
name = "arlo-tactics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arlo-domain.workspace = true
arlo-db.workspace = true
arlo-math.workspace = true
sqlx.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true