pub const BLOCK_MARKING_PROXIMITY_WEIGHT: f64 = 0.6;
pub const BLOCK_MARKING_AGGRESSION_WEIGHT: f64 = 0.4;
pub const BLOCK_MARKING_BITE_TRACKING_BOOST: f64 = 0.85;
pub const BLOCK_MARKING_COVER_DISCIPLINE_BOOST: f64 = 0.5;