pub const DUEL_PHYSICALITY_BASELINE_ARTRO_BREAKTHROUGH: f64 = 0.70;
pub const DUEL_PHYSICALITY_BASELINE_CENTRAL_BLOCK: f64 = 0.80;
pub const DUEL_PHYSICALITY_BASELINE_LATERAL_BLOCK: f64 = 0.65;
pub const DUEL_PHYSICALITY_BASELINE_BALL_SECURITY_CARRY: f64 = 0.75;
pub const DUEL_PHYSICALITY_BASELINE_BALL_SECURITY_DISTRIBUTION: f64 = 0.50;