pub const FAULT_SEVERITY_MODERATE_THRESHOLD: f64 = 0.35;
pub const FAULT_SEVERITY_SEVERE_THRESHOLD: f64 = 0.65;
pub const FAULT_SEVERITY_FLAGRANT_THRESHOLD: f64 = 0.85;

pub const FOUL_INTENSITY_CONTACT_SEVERITY_WEIGHT: f64 = 0.45;
pub const FOUL_INTENSITY_RECKLESSNESS_WEIGHT: f64 = 0.35;
pub const FOUL_INTENSITY_DUEL_BASELINE_WEIGHT: f64 = 0.20;