pub const BASE_FOUL_TRIGGER_LOGIT: f64 = -2.8;
pub const FOUL_NET_ADVANTAGE_LOGIT_SCALE: f64 = 0.15;
pub const FOUL_RECKLESSNESS_LOGIT_SCALE: f64 = 0.45;
pub const FOUL_FATIGUE_LOGIT_SCALE: f64 = 0.30;
pub const FOUL_LEVERAGE_LOGIT_SCALE: f64 = 0.25;
pub const FOUL_REFEREE_RIGOR_LOGIT_SCALE: f64 = 0.10;
pub const FOUL_REFEREE_CONSISTENCY_NOISE_SCALE: f64 = 0.35;
pub const FOUL_ATTRIBUTION_STEEPNESS: f64 = 0.20;