pub const BASE_NON_CONTACT_INJURY_HAZARD_RATE: f64 = 0.0008;
pub const BASE_CONTACT_INJURY_PROBABILITY: f64 = 0.015;

pub const INJURY_SEVERITY_GRADE_2_THRESHOLD: f64 = 0.45;
pub const INJURY_SEVERITY_GRADE_3_THRESHOLD: f64 = 0.80;

pub const AGE_INFLECTION_POINT_YEARS: f64 = 29.0;
pub const AGE_RISK_LOGISTIC_SLOPE: f64 = 0.35;
pub const AGE_MAX_RISK_MULTIPLIER: f64 = 2.0;

pub const PROTECTIVE_STRENGTH_WEIGHT: f64 = 0.25;
pub const PROTECTIVE_BALANCE_WEIGHT: f64 = 0.20;
pub const PROTECTIVE_AGILITY_WEIGHT: f64 = 0.20;
pub const PROTECTIVE_NATURAL_FITNESS_WEIGHT: f64 = 0.20;
pub const PROTECTIVE_STAMINA_WEIGHT: f64 = 0.15;

pub const CONTACT_COLLISION_INTENSITY_WEIGHT: f64 = 0.50;
pub const CONTACT_FATIGUE_WEIGHT: f64 = 0.30;
pub const CONTACT_VULNERABILITY_WEIGHT: f64 = 0.20;

pub const NON_CONTACT_FATIGUE_WEIGHT: f64 = 0.45;
pub const NON_CONTACT_VELOCITY_WEIGHT: f64 = 0.35;
pub const NON_CONTACT_DECELERATION_WEIGHT: f64 = 0.20;

pub const DEFAULT_INJURY_SUSCEPTIBILITY_MULTIPLIER: f64 = 1.0;