pub const KICK_BLOCK_ATTEMPT_LOGISTIC_FACTOR: f64 = 0.25;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_FIRST_ZONE: f64 = 0.85;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_STANDARD: f64 = 0.50;
pub const KICK_FOUL_REALIGNMENT_VALUE_STEEPNESS: f64 = 3.0;