pub const KICK_BLOCK_ATTEMPT_LOGISTIC_FACTOR: f64 = 0.25;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_FIRST_ZONE: f64 = 0.85;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_STANDARD: f64 = 0.50;
pub const KICK_FOUL_REALIGNMENT_VALUE_STEEPNESS: f64 = 3.0;
pub const KICK_FOUL_CROSS_LATERAL_BIAS_BASE: f64 = 0.70;
pub const KICK_FOUL_CROSS_LATERAL_BIAS_SCALE: f64 = 0.60;