pub const SIGNAL_DETECTION_BASE_SENSITIVITY: f64 = 1.0;
pub const SIGNAL_DETECTION_JUDGMENT_ATTRIBUTE_SCALE: f64 = 0.10;
pub const DECISION_THRESHOLD_LOGIT_STEEPNESS: f64 = 4.0;

pub const DECISION_COOLDOWN_MIN_PERIOD_FRACTION: f64 = 0.03;
pub const DECISION_COOLDOWN_MAX_PERIOD_FRACTION: f64 = 0.15;
pub const BELIEF_PRIOR_STRENGTH_MIN: f64 = 2.0;
pub const BELIEF_PRIOR_STRENGTH_MAX: f64 = 10.0;
pub const BELIEF_EVIDENCE_DECAY_MIN: f64 = 0.85;
pub const BELIEF_EVIDENCE_DECAY_MAX: f64 = 0.98;
pub const MANAGER_NOISE_DISCIPLINE_SCALE: f64 = 0.5;
pub const LEVERAGE_DEFICIT_DECAY: f64 = 0.15;
pub const LEVERAGE_DRIVE_SCARCITY_WEIGHT: f64 = 0.4;
pub const LEVERAGE_MAX: f64 = 5.0;
pub const PROJECTION_MOMENTUM_TO_SCORE_SCALE: f64 = 0.25;
pub const CHALLENGE_LEVERAGE_WEIGHT: f64 = 0.35;