use crate::domain::sport_constants::ability::{ATTRIBUTE_MAX, ATTRIBUTE_MIN};

pub const DECISION_COOLDOWN_MIN_PERIOD_FRACTION: f64 = 0.03;
pub const DECISION_COOLDOWN_MAX_PERIOD_FRACTION: f64 = 0.15;
pub const BELIEF_PRIOR_STRENGTH_MIN: f64 = 2.0;
pub const BELIEF_PRIOR_STRENGTH_MAX: f64 = 10.0;
pub const BELIEF_EVIDENCE_DECAY_MIN: f64 = 0.85;
pub const BELIEF_EVIDENCE_DECAY_MAX: f64 = 0.98;
pub const MANAGER_NOISE_DISCIPLINE_SCALE: f64 = 0.5;
pub const LEVERAGE_DEFICIT_DECAY: f64 = 0.15;
pub const LEVERAGE_DRIVE_SCARCITY_WEIGHT: f64 = 0.4;
pub const LEVERAGE_MAX: f64 = 5.0;
pub const PROJECTION_MOMENTUM_TO_SCORE_SCALE: f64 = 0.25;
pub const CHALLENGE_LEVERAGE_WEIGHT: f64 = 0.35;

pub const CHALLENGE_JUDGMENT_COMPOSITE_WEIGHT: f64 = 0.6;
pub const JUDGING_ABILITY_COMPOSITE_WEIGHT: f64 = 0.4;

pub const ADAPTABILITY_FLEXIBILITY_WEIGHT: f64 = 0.65;
pub const BASE_FLEXIBILITY_WEIGHT: f64 = 0.35;
pub const IN_GAME_ADJUSTMENT_MAX_IMPACT: f64 = 0.25;
pub const ROTATION_POLICY_FATIGUE_THRESHOLD_STRICT: f64 = 0.85;
pub const ROTATION_POLICY_FATIGUE_THRESHOLD_SITUATIONAL: f64 = 0.70;
pub const ROTATION_POLICY_FATIGUE_THRESHOLD_HIGH: f64 = 0.55;
pub const MAX_PREFERRED_FORMATIONS: usize = 3;
pub const LAUNCHER_PASSING_RANGE_PREFERENCE_WEIGHT: f64 = 0.25;
pub const BLOCKER_ROLE_BASE_THRESHOLD: f64 = 14.0;
pub const BLOCKER_ROLE_PHYSICALITY_ADJUSTMENT: f64 = 4.0;

pub const SUBSTITUTION_FATIGUE_URGENCY_ROTATION_WEIGHT: f64 = 0.40;
pub const SUBSTITUTION_TACTICAL_URGENCY_DEFICIT_WEIGHT: f64 = 0.25;
pub const SUBSTITUTION_DISCIPLINARY_URGENCY_WEIGHT: f64 = 0.35;
pub const DISCIPLINARY_SUSPENSION_URGENCY: f64 = 1.0;
pub const DISCIPLINARY_ACTIVE_URGENCY: f64 = 0.0;
pub const SUBSTITUTION_LOAD_MANAGEMENT_PROACTIVITY_SCALE: f64 = 0.15;
pub const SUBSTITUTION_LEVERAGE_WEIGHT: f64 = 0.25;

pub const PROFILE_SWITCH_FIT_MARGIN_BASE: f64 = 0.15;
pub const PROFILE_SWITCH_FLEXIBILITY_SCALE: f64 = 0.10;

pub const TIME_CALL_FATIGUE_URGENCY_WEIGHT: f64 = 0.45;
pub const TIME_CALL_MOMENTUM_URGENCY_WEIGHT: f64 = 0.35;
pub const TIME_CALL_ENDGAME_RESERVE_BIAS: f64 = 0.50;
pub const TIME_CALL_ENDGAME_THRESHOLD_SECONDS: f64 = 600.0;
pub const TIME_CALL_JUST_CONCEDED_BONUS: f64 = 0.40;
pub const TIME_CALL_PRESSURE_WEIGHT: f64 = 0.20;
pub const TIME_CALL_LEVERAGE_WEIGHT: f64 = 0.25;

pub fn effective_manager_flexibility(
    adaptability_attribute: f64,
    flexibility_tendency: f64,
) -> f64 {
    let normalized_adaptability = (adaptability_attribute.clamp(ATTRIBUTE_MIN, ATTRIBUTE_MAX)
        - ATTRIBUTE_MIN)
        / (ATTRIBUTE_MAX - ATTRIBUTE_MIN);
    let raw = (normalized_adaptability * ADAPTABILITY_FLEXIBILITY_WEIGHT)
        + (flexibility_tendency.clamp(0.0, 1.0) * BASE_FLEXIBILITY_WEIGHT);
    raw.clamp(0.0, 1.0)
}
