pub const REGULAR_PERIODS_COUNT: u32 = 4;
pub const PERIOD_DURATION_MINUTES: u32 = 30;
pub const TOTAL_REGULAR_MINUTES: u32 = REGULAR_PERIODS_COUNT * PERIOD_DURATION_MINUTES;
pub const OVERTIME_PERIODS_COUNT: u32 = 2;
pub const OVERTIME_PERIOD_DURATION_MINUTES: u32 = 15;
pub const TIME_CALLS_PER_PERIOD: u32 = 3;
pub const TIME_CALL_DURATION_MINUTES: u32 = 5;
pub const CHALLENGE_CALLS_PER_MATCH: u32 = 3;
pub const IMMEDIATE_POSSESSION_CONTROL_SECONDS: f64 = 0.7;

pub const MAX_CALL_TO_ACTIONS_PER_SERIES: u32 = 4;
pub const MINIMUM_ADVANCE_MIRINS_PER_SERIES: f64 = 10.0;
pub const DEFAULT_BONUS_PHASE_MAX_PLAYS: u32 = 1;
pub const BONUS_FIELDPOST_DISTANCE_TO_GOAL_MIRIM: f64 = 14.0;
pub const BONUS_GOALPOST_DISTANCE_TO_GOAL_MIRIM: f64 = 2.0;

pub const GOAL_POINT_VALUE: i32 = 5;
pub const FIELD_POINT_VALUE: i32 = 3;
pub const FIELD_GOAL_GOALPOST_VALUE: i32 = 2;
pub const FIELD_GOAL_FIELDPOST_VALUE: i32 = 1;
pub const ARTROS_PER_DRIVE: u32 = 3;
pub const GOAL_POINT_REQUIRED_DRIVES: u32 = 1;
