pub const MAX_ADDED_TIME_SECONDS: f64 = 1800.0;
pub const ADDED_TIME_BASELINE_DEAD_BALL_SECONDS: f64 = 1000.0;
pub const ADDED_TIME_DEAD_BALL_EXCESS_WEIGHT: f64 = 0.03;
pub const ADDED_TIME_FOUL_WEIGHT_SECONDS: f64 = 8.0;
pub const ADDED_TIME_INJURY_WEIGHT_SECONDS: f64 = 45.0;
pub const ADDED_TIME_CHALLENGE_WEIGHT_SECONDS: f64 = 20.0;
pub const ADDED_TIME_TIME_CALL_WEIGHT_SECONDS: f64 = 10.0;
pub const ADDED_TIME_KICK_FOUL_WEIGHT_SECONDS: f64 = 12.0;
pub const ADDED_TIME_SCORING_WEIGHT_SECONDS: f64 = 15.0;
pub const ADDED_TIME_FIRST_HALF_MULTIPLIER: f64 = 0.85;
pub const ADDED_TIME_SECOND_HALF_MULTIPLIER: f64 = 1.15;
pub const ADDED_TIME_OVERTIME_MULTIPLIER: f64 = 0.6;
pub const ADDED_TIME_BASE_RECOGNITION_SCALE: f64 = 0.7;
pub const ADDED_TIME_RIGOR_RECOGNITION_SCALE: f64 = 0.2;
pub const ADDED_TIME_AUTHORITY_RECOGNITION_SCALE: f64 = 0.15;
pub const ADDED_TIME_CONSISTENCY_NOISE_SCALE_SECONDS: f64 = 25.0;

pub const FAULT_SEVERITY_MODERATE_THRESHOLD: f64 = 0.35;
pub const FAULT_SEVERITY_SEVERE_THRESHOLD: f64 = 0.65;
pub const FAULT_SEVERITY_FLAGRANT_THRESHOLD: f64 = 0.85;

pub const FOUL_INTENSITY_CONTACT_SEVERITY_WEIGHT: f64 = 0.45;
pub const FOUL_INTENSITY_RECKLESSNESS_WEIGHT: f64 = 0.35;
pub const FOUL_INTENSITY_DUEL_BASELINE_WEIGHT: f64 = 0.20;

pub const FOUL_IMPULSE_EPV_DELTA: f64 = 2.5;
pub const FOUL_CHALLENGE_PUNISHMENT_SEVERITY_WEIGHT: f64 = 0.15;

pub const BASE_FOUL_TRIGGER_LOGIT: f64 = -2.8;
pub const FOUL_NET_ADVANTAGE_LOGIT_SCALE: f64 = 0.15;
pub const FOUL_RECKLESSNESS_LOGIT_SCALE: f64 = 0.45;
pub const FOUL_FATIGUE_LOGIT_SCALE: f64 = 0.30;
pub const FOUL_LEVERAGE_LOGIT_SCALE: f64 = 0.25;
pub const FOUL_REFEREE_RIGOR_LOGIT_SCALE: f64 = 0.10;
pub const FOUL_REFEREE_CONSISTENCY_NOISE_SCALE: f64 = 0.35;
pub const FOUL_ATTRIBUTION_STEEPNESS: f64 = 0.20;

pub const FIRST_ZONE_FOUL_SEVERITY_MULTIPLIER: f64 = 1.30;

pub const PEACE_REFEREE_BASE_SENSITIVITY: f64 = 1.0;
pub const PEACE_REFEREE_AUTHORITY_SCALE: f64 = 0.10;
pub const PEACE_REFEREE_INTERVENTION_STEEPNESS: f64 = 4.0;

pub const DEFAULT_LOSS_OF_DOWN_COUNT: i32 = 1;
pub const DEFAULT_YARDAGE_LOSS_MIRIM: f64 = 5.0;
pub const DEFAULT_LOSS_OF_DRIVE_COUNT: i32 = 1;
pub const DEFAULT_TIME_PENALTY_MINUTES: i32 = 2;

pub const PUNISHMENT_SEVERITY_YARDAGE_LOSS: f64 = 1.0;
pub const PUNISHMENT_SEVERITY_LOSS_OF_DOWN: f64 = 1.5;
pub const PUNISHMENT_SEVERITY_LOSS_OF_DRIVE: f64 = 2.0;
pub const PUNISHMENT_SEVERITY_KICK_FOUL_AWARDED: f64 = 2.2;
pub const PUNISHMENT_SEVERITY_TIME_PENALTY: f64 = 1.2;
pub const PUNISHMENT_SEVERITY_EXPULSION: f64 = 3.0;
pub const PUNISHMENT_SEVERITY_INVALIDATE_PREVIOUS_PLAY: f64 = 1.8;

pub const KICK_BLOCK_ATTEMPT_LOGISTIC_FACTOR: f64 = 0.25;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_FIRST_ZONE: f64 = 0.85;
pub const KICK_FOUL_SHOOT_GOAL_POINT_BIAS_WEIGHT_STANDARD: f64 = 0.50;
pub const KICK_FOUL_REALIGNMENT_VALUE_STEEPNESS: f64 = 3.0;
pub const KICK_FOUL_CROSS_LATERAL_BIAS_BASE: f64 = 0.70;
pub const KICK_FOUL_CROSS_LATERAL_BIAS_SCALE: f64 = 0.60;