pub const SHORT_PASS_RANGE_SENSITIVITY: f64 = 0.35;
pub const LONG_LAUNCH_RANGE_SENSITIVITY: f64 = 0.35;
pub const SHORT_PASS_BASE_ADVANCE_MIRIM: f64 = 4.0;
pub const SHORT_PASS_MIN_ADVANCE_MIRIM: f64 = 1.0;
pub const LONG_LAUNCH_BASE_ADVANCE_MIRIM: f64 = 12.0;
pub const LONG_LAUNCH_MIN_ADVANCE_MIRIM: f64 = 3.0;