pub const ARTRINE_DECISION_LOGIT_STEEPNESS: f64 = 0.25;
pub const RANGE_UTILITY_SCALE: f64 = 2.0;
pub const DRIVES_NEEDED_UTILITY_SCALE: f64 = 2.5;
pub const DOWN_PRESSURE_UTILITY_SCALE: f64 = 1.5;
pub const PRESSURE_READ_UTILITY_SCALE: f64 = 1.8;
pub const LAST_DOWN_DESPERATION_UTILITY_SCALE: f64 = 3.0;