pub const PUNISHMENT_SEVERITY_YARDAGE_LOSS: f64 = 1.0;
pub const PUNISHMENT_SEVERITY_LOSS_OF_DOWN: f64 = 1.5;
pub const PUNISHMENT_SEVERITY_LOSS_OF_DRIVE: f64 = 2.0;
pub const PUNISHMENT_SEVERITY_KICK_FOUL_AWARDED: f64 = 2.2;
pub const PUNISHMENT_SEVERITY_TIME_PENALTY: f64 = 1.2;
pub const PUNISHMENT_SEVERITY_EXPULSION: f64 = 3.0;
pub const PUNISHMENT_SEVERITY_INVALIDATE_PREVIOUS_PLAY: f64 = 1.8;