pub const CONTRAST_LOGISTIC_SLOPE: f64 = 0.15;
pub const BASE_NOISE_SCALE: f64 = 0.5;
pub const HOME_FIELD_ADVANTAGE_LOGIT: f64 = 0.2;
pub const GROUP_SATURATION_THRESHOLD: f64 = 2.0;
pub const GROUP_SATURATION_MULTIPLIER: f64 = 0.5;
pub const GROUP_AGGREGATION_SATURATION_THRESHOLD: f64 = 2.0;
pub const GROUP_AGGREGATION_SATURATION_MULTIPLIER: f64 = 0.5;