pub const CONTRAST_LOGISTIC_SLOPE: f64 = 0.28;
pub const BASE_NOISE_SCALE: f64 = 0.25;
pub const GROUP_SATURATION_THRESHOLD: f64 = 2.0;
pub const GROUP_SATURATION_MULTIPLIER: f64 = 0.5;
pub const GROUP_AGGREGATION_SATURATION_THRESHOLD: f64 = 2.0;
pub const GROUP_AGGREGATION_SATURATION_MULTIPLIER: f64 = 0.5;
pub const MISDIRECTION_MAX_LOGIT_MULTIPLIER: f64 = 1.5;

pub const DUEL_PHYSICALITY_BASELINE_ARTRO_BREAKTHROUGH: f64 = 0.70;
pub const DUEL_PHYSICALITY_BASELINE_CENTRAL_BLOCK: f64 = 0.80;
pub const DUEL_PHYSICALITY_BASELINE_LATERAL_BLOCK: f64 = 0.65;
pub const DUEL_PHYSICALITY_BASELINE_BALL_SECURITY_CARRY: f64 = 0.75;
pub const DUEL_PHYSICALITY_BASELINE_BALL_SECURITY_DISTRIBUTION: f64 = 0.50;
