pub const KICK_POST_RATING_NORMALIZATION_CAP: f64 = 20.0;
pub const KICK_POST_DISTANCE_NORMALIZATION_CAP: f64 = 10.0;
pub const KICK_POST_RATING_WEIGHT: f64 = 0.6;
pub const KICK_POST_DISTANCE_WEIGHT: f64 = 0.4;
pub const KICK_POST_GOALPOST_SCORE_THRESHOLD: f64 = 0.5;