pub const SPATIAL_TICK_DURATION_SECONDS: f64 = 0.1;
pub const PROXIMITY_CONTEST_RADIUS_MIRIM: f64 = 2.0;
pub const MAX_OPEN_PLAY_TICKS: u32 = 300;
pub const TARGET_ARRIVAL_TOLERANCE_MIRIM: f64 = 0.25;