pub const SUBSTITUTION_FATIGUE_URGENCY_ROTATION_WEIGHT: f64 = 0.40;
pub const SUBSTITUTION_TACTICAL_URGENCY_DEFICIT_WEIGHT: f64 = 0.25;
pub const SUBSTITUTION_DISCIPLINARY_URGENCY_WEIGHT: f64 = 0.35;
pub const DISCIPLINARY_SUSPENSION_URGENCY: f64 = 1.0;
pub const DISCIPLINARY_ACTIVE_URGENCY: f64 = 0.0;
pub const SUBSTITUTION_LOAD_MANAGEMENT_PROACTIVITY_SCALE: f64 = 0.15;
pub const SUBSTITUTION_LEVERAGE_WEIGHT: f64 = 0.25;