pub const TIME_CALL_FATIGUE_URGENCY_WEIGHT: f64 = 0.45;
pub const TIME_CALL_MOMENTUM_URGENCY_WEIGHT: f64 = 0.35;
pub const TIME_CALL_ENDGAME_RESERVE_BIAS: f64 = 0.50;
pub const TIME_CALL_ENDGAME_THRESHOLD_SECONDS: f64 = 600.0;
pub const TIME_CALL_JUST_CONCEDED_BONUS: f64 = 0.40;
pub const TIME_CALL_PRESSURE_WEIGHT: f64 = 0.20;
pub const TIME_CALL_LEVERAGE_WEIGHT: f64 = 0.25;
