pub mod artrine_decisions_repository;
pub mod assists_repository;
pub mod availability_repository;
pub mod drives_repository;
pub mod duels_repository;
pub mod fouls_repository;
pub mod impulse_repository;
pub mod injuries_repository;
pub mod kick_fouls_repository;
pub mod physical_repository;
pub mod punishments_repository;
pub mod receiving_repository;
pub mod scoring_attempts_repository;
pub mod touches_repository;

pub use artrine_decisions_repository as match_player_artrine_decisions;
pub use assists_repository as match_player_assists;
pub use availability_repository as match_player_availability;
pub use drives_repository as match_player_drives;
pub use duels_repository as match_player_duels;
pub use fouls_repository as match_player_fouls;
pub use impulse_repository as match_player_impulse;
pub use injuries_repository as match_player_injuries;
pub use kick_fouls_repository as match_player_kick_fouls;
pub use physical_repository as match_player_physical;
pub use punishments_repository as match_player_punishments;
pub use receiving_repository as match_player_receiving;
pub use scoring_attempts_repository as match_player_scoring_attempts;
pub use touches_repository as match_player_touches;
