use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum AttributeKey {
    ArloControl,
    Passing,
    Dribbling,
    Finishing,
    Crossing,
    OffensiveBlocking,
    DefensiveContainment,
    PasserPressure,
    HandsReception,
    DriveTechnique,
    FalseArtrineBluff,
    Technique,
    Anticipation,
    Decisions,
    Composure,
    Concentration,
    Vision,
    Positioning,
    Teamwork,
    Determination,
    Leadership,
    ControlledAggression,
    Bravery,
    Flair,
    WorkRate,
    Consistency,
    Acceleration,
    Pace,
    Agility,
    Balance,
    Strength,
    Stamina,
    JumpingReach,
    NaturalFitness,
    Reflexes,
    Handling,
    AreaCommand,
    Communication,
    OneOnOne,
    Distribution,
    GoalKicking,
    RushingOut,
    TacticalKnowledge,
    OffensePlanning,
    DefenseOrganization,
    ArtroStrategy,
    Adaptability,
    ArtrineCommunication,
    TimeCallManagement,
    ChallengeJudgment,
    InGameAdjustments,
    ManManagement,
    LoadManagement,
    PlayerDevelopment,
    JudgingAbility,
    JudgingPotential,
    Discipline,
}

impl AttributeKey {
    pub const COUNT: usize = 57;

    pub const fn all() -> [AttributeKey; Self::COUNT] {
        [
            AttributeKey::ArloControl,
            AttributeKey::Passing,
            AttributeKey::Dribbling,
            AttributeKey::Finishing,
            AttributeKey::Crossing,
            AttributeKey::OffensiveBlocking,
            AttributeKey::DefensiveContainment,
            AttributeKey::PasserPressure,
            AttributeKey::HandsReception,
            AttributeKey::DriveTechnique,
            AttributeKey::FalseArtrineBluff,
            AttributeKey::Technique,
            AttributeKey::Anticipation,
            AttributeKey::Decisions,
            AttributeKey::Composure,
            AttributeKey::Concentration,
            AttributeKey::Vision,
            AttributeKey::Positioning,
            AttributeKey::Teamwork,
            AttributeKey::Determination,
            AttributeKey::Leadership,
            AttributeKey::ControlledAggression,
            AttributeKey::Bravery,
            AttributeKey::Flair,
            AttributeKey::WorkRate,
            AttributeKey::Consistency,
            AttributeKey::Acceleration,
            AttributeKey::Pace,
            AttributeKey::Agility,
            AttributeKey::Balance,
            AttributeKey::Strength,
            AttributeKey::Stamina,
            AttributeKey::JumpingReach,
            AttributeKey::NaturalFitness,
            AttributeKey::Reflexes,
            AttributeKey::Handling,
            AttributeKey::AreaCommand,
            AttributeKey::Communication,
            AttributeKey::OneOnOne,
            AttributeKey::Distribution,
            AttributeKey::GoalKicking,
            AttributeKey::RushingOut,
            AttributeKey::TacticalKnowledge,
            AttributeKey::OffensePlanning,
            AttributeKey::DefenseOrganization,
            AttributeKey::ArtroStrategy,
            AttributeKey::Adaptability,
            AttributeKey::ArtrineCommunication,
            AttributeKey::TimeCallManagement,
            AttributeKey::ChallengeJudgment,
            AttributeKey::InGameAdjustments,
            AttributeKey::ManManagement,
            AttributeKey::LoadManagement,
            AttributeKey::PlayerDevelopment,
            AttributeKey::JudgingAbility,
            AttributeKey::JudgingPotential,
            AttributeKey::Discipline,
        ]
    }

    pub const fn index(self) -> usize {
        match self {
            AttributeKey::ArloControl => 0,
            AttributeKey::Passing => 1,
            AttributeKey::Dribbling => 2,
            AttributeKey::Finishing => 3,
            AttributeKey::Crossing => 4,
            AttributeKey::OffensiveBlocking => 5,
            AttributeKey::DefensiveContainment => 6,
            AttributeKey::PasserPressure => 7,
            AttributeKey::HandsReception => 8,
            AttributeKey::DriveTechnique => 9,
            AttributeKey::FalseArtrineBluff => 10,
            AttributeKey::Technique => 11,
            AttributeKey::Anticipation => 12,
            AttributeKey::Decisions => 13,
            AttributeKey::Composure => 14,
            AttributeKey::Concentration => 15,
            AttributeKey::Vision => 16,
            AttributeKey::Positioning => 17,
            AttributeKey::Teamwork => 18,
            AttributeKey::Determination => 19,
            AttributeKey::Leadership => 20,
            AttributeKey::ControlledAggression => 21,
            AttributeKey::Bravery => 22,
            AttributeKey::Flair => 23,
            AttributeKey::WorkRate => 24,
            AttributeKey::Consistency => 25,
            AttributeKey::Acceleration => 26,
            AttributeKey::Pace => 27,
            AttributeKey::Agility => 28,
            AttributeKey::Balance => 29,
            AttributeKey::Strength => 30,
            AttributeKey::Stamina => 31,
            AttributeKey::JumpingReach => 32,
            AttributeKey::NaturalFitness => 33,
            AttributeKey::Reflexes => 34,
            AttributeKey::Handling => 35,
            AttributeKey::AreaCommand => 36,
            AttributeKey::Communication => 37,
            AttributeKey::OneOnOne => 38,
            AttributeKey::Distribution => 39,
            AttributeKey::GoalKicking => 40,
            AttributeKey::RushingOut => 41,
            AttributeKey::TacticalKnowledge => 42,
            AttributeKey::OffensePlanning => 43,
            AttributeKey::DefenseOrganization => 44,
            AttributeKey::ArtroStrategy => 45,
            AttributeKey::Adaptability => 46,
            AttributeKey::ArtrineCommunication => 47,
            AttributeKey::TimeCallManagement => 48,
            AttributeKey::ChallengeJudgment => 49,
            AttributeKey::InGameAdjustments => 50,
            AttributeKey::ManManagement => 51,
            AttributeKey::LoadManagement => 52,
            AttributeKey::PlayerDevelopment => 53,
            AttributeKey::JudgingAbility => 54,
            AttributeKey::JudgingPotential => 55,
            AttributeKey::Discipline => 56,
        }
    }
}
