pub const LINE_PLAYERS_PER_TEAM: u32 = 13;
pub const GOALGUARDS_PER_TEAM: u32 = 1;
pub const TOTAL_PLAYERS_PER_TEAM: u32 = LINE_PLAYERS_PER_TEAM + GOALGUARDS_PER_TEAM;
pub const PITCH_LENGTH_MIRIM_MIN: f64 = 140.0;
pub const PITCH_LENGTH_MIRIM_MAX: f64 = 150.0;
pub const PITCH_WIDTH_MIRIM_MIN: f64 = 80.0;
pub const PITCH_WIDTH_MIRIM_MAX: f64 = 90.0;