pub const DRIVES_THRESHOLD_FOR_SCORING_OPPORTUNITY: u32 = 3;
pub const CARRY_EARLY_DRIVE_BONUS_MULTIPLIER: f64 = 0.35;
pub const MIN_DECISION_BIAS: f64 = 0.10;
pub const MAX_DECISION_BIAS: f64 = 4.00;

pub const DEFAULT_TOTAL_REMAINING_SECONDS: f64 = 3600.0;
pub const DEFAULT_PRESSURE_BIAS: f64 = 1.0;

pub const URGENCY_TIME_HALF_LIFE_SECONDS: f64 = 360.0;
pub const URGENCY_POWER_CURVE: f64 = 1.4;

pub const TRAILING_URGENCY_DEFICIT_FACTOR: f64 = 0.35;
pub const TRAILING_URGENCY_BASE_WEIGHT: f64 = 0.30;
pub const TRAILING_URGENCY_TIME_WEIGHT: f64 = 0.70;
pub const MAX_TRAILING_URGENCY_INDEX: f64 = 5.0;

pub const LEADING_URGENCY_DEFICIT_FACTOR: f64 = 0.20;
pub const MAX_LEADING_URGENCY_INDEX: f64 = 3.0;

pub const TIED_URGENCY_BASE_FACTOR: f64 = 0.50;
pub const MAX_TIED_URGENCY_INDEX: f64 = 2.0;

pub const LARGE_DEFICIT_THRESHOLD: i32 = 4;
pub const URGENCY_THRESHOLD: f64 = 0.35;
pub const URGENCY_INTENSITY_DIVISOR: f64 = 0.65;

pub const LARGE_DEFICIT_GOAL_POINT_SCALE: f64 = 2.20;
pub const LARGE_DEFICIT_GOAL_POINT_MAX: f64 = 3.50;
pub const LARGE_DEFICIT_FIELD_POINT_SCALE: f64 = 0.75;
pub const LARGE_DEFICIT_FIELD_POINT_MIN: f64 = 0.15;
pub const LARGE_DEFICIT_LONG_LAUNCH_SCALE: f64 = 0.70;
pub const LARGE_DEFICIT_LONG_LAUNCH_MAX: f64 = 2.20;
pub const LARGE_DEFICIT_CROSS_SCALE: f64 = 0.90;
pub const LARGE_DEFICIT_CROSS_MAX: f64 = 2.40;
pub const LARGE_DEFICIT_SELF_FINISH_SCALE: f64 = 0.85;
pub const LARGE_DEFICIT_SELF_FINISH_MAX: f64 = 2.20;
pub const LARGE_DEFICIT_SHORT_PASS_SCALE: f64 = 0.35;
pub const LARGE_DEFICIT_SHORT_PASS_MIN: f64 = 0.45;
pub const LARGE_DEFICIT_CARRY_SCALE: f64 = 0.25;
pub const LARGE_DEFICIT_CARRY_MIN: f64 = 0.55;
pub const LARGE_DEFICIT_TURNOVER_AVERSION_SCALE: f64 = 0.45;
pub const LARGE_DEFICIT_TURNOVER_AVERSION_MIN: f64 = 0.35;

pub const SMALL_DEFICIT_GOAL_POINT_SCALE: f64 = 0.80;
pub const SMALL_DEFICIT_GOAL_POINT_MAX: f64 = 2.00;
pub const SMALL_DEFICIT_FIELD_POINT_SCALE: f64 = 1.40;
pub const SMALL_DEFICIT_FIELD_POINT_MAX: f64 = 2.60;
pub const SMALL_DEFICIT_LONG_LAUNCH_SCALE: f64 = 0.20;
pub const SMALL_DEFICIT_LONG_LAUNCH_MAX: f64 = 1.40;
pub const SMALL_DEFICIT_CROSS_SCALE: f64 = 0.70;
pub const SMALL_DEFICIT_CROSS_MAX: f64 = 2.00;
pub const SMALL_DEFICIT_SELF_FINISH_SCALE: f64 = 0.60;
pub const SMALL_DEFICIT_SELF_FINISH_MAX: f64 = 1.90;
pub const SMALL_DEFICIT_SHORT_PASS_SCALE: f64 = 0.15;
pub const SMALL_DEFICIT_SHORT_PASS_MAX: f64 = 1.30;
pub const SMALL_DEFICIT_CARRY_SCALE: f64 = 0.10;
pub const SMALL_DEFICIT_CARRY_MAX: f64 = 1.25;
pub const SMALL_DEFICIT_TURNOVER_AVERSION_SCALE: f64 = 0.35;
pub const SMALL_DEFICIT_TURNOVER_AVERSION_MAX: f64 = 1.80;

pub const LEADING_GOAL_POINT_SCALE: f64 = 0.35;
pub const LEADING_GOAL_POINT_MIN: f64 = 0.45;
pub const LEADING_LONG_LAUNCH_SCALE: f64 = 0.55;
pub const LEADING_LONG_LAUNCH_MIN: f64 = 0.35;
pub const LEADING_CROSS_SCALE: f64 = 0.45;
pub const LEADING_CROSS_MIN: f64 = 0.40;
pub const LEADING_SELF_FINISH_SCALE: f64 = 0.35;
pub const LEADING_SELF_FINISH_MIN: f64 = 0.50;
pub const LEADING_SHORT_PASS_SCALE: f64 = 0.45;
pub const LEADING_SHORT_PASS_MAX: f64 = 1.70;
pub const LEADING_CARRY_SCALE: f64 = 0.55;
pub const LEADING_CARRY_MAX: f64 = 1.85;
pub const LEADING_TURNOVER_AVERSION_SCALE: f64 = 1.10;
pub const LEADING_TURNOVER_AVERSION_MAX: f64 = 2.60;

pub const PITCH_EDGE_MARGIN_MIRIM: f64 = 0.5;
pub const COUNTER_PRESS_SHIFT_PERCENTAGE: f64 = 0.08;
pub const DEFAULT_ATTRIBUTE_VALUE: f64 = 10.0;
pub const HUDDLE_BASE_MAX_SECONDS: f64 = 28.0;
pub const HUDDLE_TACTICAL_WEIGHT: f64 = 0.55;
pub const HUDDLE_LEADERSHIP_WEIGHT: f64 = 0.45;
pub const HUDDLE_MIN_SECONDS: f64 = 8.0;
pub const HUDDLE_MAX_SECONDS: f64 = 32.0;

pub const IMMEDIATE_CONTROL_THRESHOLD_SECONDS: f64 = 0.7;
