use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlayerMatchSnapshot {
    pub player_id: Uuid,
    pub total_touches: u32,
    pub passes_attempted: u32,
    pub passes_received: u32,
    pub recoveries: u32,
    pub turnovers_conceded: u32,
    pub total_drives: u32,
    pub central_drives: u32,
    pub left_lateral_drives: u32,
    pub right_lateral_drives: u32,
    pub lateral_drives: u32,
    pub max_drives_in_series: u32,
    pub total_duels: u32,
    pub total_duel_wins: u32,
    pub total_duel_losses: u32,
    pub duel_win_rate: f64,
    pub attacker_duels: u32,
    pub attacker_duel_wins: u32,
    pub attacker_duel_losses: u32,
    pub attacker_duel_win_rate: f64,
    pub defender_duels: u32,
    pub defender_duel_wins: u32,
    pub defender_duel_losses: u32,
    pub defender_duel_win_rate: f64,
    pub targets: u32,
    pub receptions: u32,
    pub drops: u32,
    pub catch_rate: f64,
    pub drop_rate: f64,
    pub receiving_mirins: f64,
    pub run_after_catch_mirins: f64,
    pub longest_reception_mirim: f64,
    pub average_mirins_per_reception: f64,
    pub scoring_attempts: u32,
    pub scoring_conversions: u32,
    pub scoring_misses: u32,
    pub scoring_conversion_rate: f64,
    pub goal_points_scored: u32,
    pub field_points_scored: u32,
    pub field_goals_scored: u32,
    pub total_points_scored: u32,
    pub goalpoint_assists: u32,
    pub artrine_decisions_total: u32,
    pub artrine_decisions_successful: u32,
    pub artrine_decisions_failed: u32,
    pub artrine_success_rate: f64,
    pub artrine_mirins_advanced: f64,
    pub artrine_points_generated: u32,
    pub artrine_goal_points_generated: u32,
    pub artrine_field_points_generated: u32,
    pub artrine_field_goals_generated: u32,
    pub end_energy_level: f64,
    pub peak_anaerobic_depletion: f64,
    pub total_distance_covered: f64,
    pub high_intensity_distance: f64,
    pub low_intensity_distance: f64,
    pub metabolic_energy_joules: f64,
    pub peak_speed_meters_per_sec: f64,
    pub intra_match_recovery_amount: f64,
    pub distance_first_zone: f64,
    pub distance_second_zone: f64,
    pub distance_corridors: f64,
    pub distance_central: f64,
    pub impulse_baseline: f64,
    pub impulse_current: u8,
    pub impulse_min: u8,
    pub impulse_max: u8,
    pub impulse_average: f64,
    pub impulse_shifts_total: u32,
    pub impulse_time_below_baseline_seconds: f64,
    pub impulse_runs_count: u32,
    pub impulse_longest_run_seconds: f64,
    pub impulse_peak_run_value: u8,
    pub impulse_total_run_intensity: f64,
}

impl PlayerMatchSnapshot {
    pub fn new(player_id: Uuid) -> Self {
        Self {
            player_id,
            ..Default::default()
        }
    }
}

impl Default for PlayerMatchSnapshot {
    fn default() -> Self {
        Self {
            player_id: Uuid::nil(),
            total_touches: 0,
            passes_attempted: 0,
            passes_received: 0,
            recoveries: 0,
            turnovers_conceded: 0,
            total_drives: 0,
            central_drives: 0,
            left_lateral_drives: 0,
            right_lateral_drives: 0,
            lateral_drives: 0,
            max_drives_in_series: 0,
            total_duels: 0,
            total_duel_wins: 0,
            total_duel_losses: 0,
            duel_win_rate: 0.0,
            attacker_duels: 0,
            attacker_duel_wins: 0,
            attacker_duel_losses: 0,
            attacker_duel_win_rate: 0.0,
            defender_duels: 0,
            defender_duel_wins: 0,
            defender_duel_losses: 0,
            defender_duel_win_rate: 0.0,
            targets: 0,
            receptions: 0,
            drops: 0,
            catch_rate: 0.0,
            drop_rate: 0.0,
            receiving_mirins: 0.0,
            run_after_catch_mirins: 0.0,
            longest_reception_mirim: 0.0,
            average_mirins_per_reception: 0.0,
            scoring_attempts: 0,
            scoring_conversions: 0,
            scoring_misses: 0,
            scoring_conversion_rate: 0.0,
            goal_points_scored: 0,
            field_points_scored: 0,
            field_goals_scored: 0,
            total_points_scored: 0,
            goalpoint_assists: 0,
            artrine_decisions_total: 0,
            artrine_decisions_successful: 0,
            artrine_decisions_failed: 0,
            artrine_success_rate: 0.0,
            artrine_mirins_advanced: 0.0,
            artrine_points_generated: 0,
            artrine_goal_points_generated: 0,
            artrine_field_points_generated: 0,
            artrine_field_goals_generated: 0,
            end_energy_level: 1.0,
            peak_anaerobic_depletion: 0.0,
            total_distance_covered: 0.0,
            high_intensity_distance: 0.0,
            low_intensity_distance: 0.0,
            metabolic_energy_joules: 0.0,
            peak_speed_meters_per_sec: 0.0,
            intra_match_recovery_amount: 0.0,
            distance_first_zone: 0.0,
            distance_second_zone: 0.0,
            distance_corridors: 0.0,
            distance_central: 0.0,
            impulse_baseline: 50.0,
            impulse_current: 50,
            impulse_min: 50,
            impulse_max: 50,
            impulse_average: 50.0,
            impulse_shifts_total: 0,
            impulse_time_below_baseline_seconds: 0.0,
            impulse_runs_count: 0,
            impulse_longest_run_seconds: 0.0,
            impulse_peak_run_value: 50,
            impulse_total_run_intensity: 0.0,
        }
    }
}
