pub const MIN_DECISION_BIAS: f64 = 0.10;
pub const MAX_DECISION_BIAS: f64 = 6.00;
pub const CARRY_EARLY_DRIVE_BONUS_MULTIPLIER: f64 = 0.35;

pub const DEFAULT_TOTAL_REMAINING_SECONDS: f64 = 3600.0;
pub const DEFAULT_PRESSURE_BIAS: f64 = 1.0;

pub const URGENCY_TIME_HALF_LIFE_SECONDS: f64 = 360.0;
pub const URGENCY_POWER_CURVE: f64 = 1.4;

pub const TRAILING_URGENCY_DEFICIT_FACTOR: f64 = 0.35;
pub const TRAILING_URGENCY_BASE_WEIGHT: f64 = 0.30;
pub const TRAILING_URGENCY_TIME_WEIGHT: f64 = 0.70;
pub const MAX_TRAILING_URGENCY_INDEX: f64 = 5.0;

pub const LEADING_URGENCY_DEFICIT_FACTOR: f64 = 0.20;
pub const MAX_LEADING_URGENCY_INDEX: f64 = 3.0;

pub const TIED_URGENCY_BASE_FACTOR: f64 = 0.50;
pub const MAX_TIED_URGENCY_INDEX: f64 = 2.0;

pub const PITCH_EDGE_MARGIN_MIRIM: f64 = 0.5;
pub const COUNTER_PRESS_SHIFT_PERCENTAGE: f64 = 0.08;
pub const DEFAULT_ATTRIBUTE_VALUE: f64 = 10.0;
pub const HUDDLE_BASE_MAX_SECONDS: f64 = 28.0;
pub const HUDDLE_TACTICAL_WEIGHT: f64 = 0.55;
pub const HUDDLE_LEADERSHIP_WEIGHT: f64 = 0.45;
pub const HUDDLE_MIN_SECONDS: f64 = 8.0;
pub const HUDDLE_MAX_SECONDS: f64 = 32.0;

pub const IMMEDIATE_CONTROL_THRESHOLD_SECONDS: f64 = 0.7;
